[package]
name = "arrix-plugin-host"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
arrix-core.workspace = true
arrix-doc.workspace = true
arrix-plugin-api.workspace = true
semver.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
serde_json.workspace = true
